channels:
  - conda-forge
  - conda-forge/label/prerelease-jupyterlab  
dependencies:
  - numpy
  - scipy
  - pandas
  - seaborn
  - matplotlib
  - bokeh
  - scikit-learn 
  - xeus-cling=0.12.0
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - jupyterlab=2
  - nodejs
  - notebook=6
  - ptvsd
  - xeus-python=0.9.0
  - nbgitpuller
  - pandoc
  - sphinx
  - nbsphinx
  - jupyterlab-git
  - voila
  - rise
  - ipysheet
  - pip
  - pip: 
    - bash_kernel
    - sphinx_rtd_theme
    - nbdime
    - yfinance
    - schedule 
    - panel
    - numdifftools
    - hvplot
    - rpy2
    - KDEpy
    - pygam
    - get-all-tickers
    - pyDiffMap
    - pdpbox
    - arch
    - xgboost
